use_frameworks!

platform :ios, '10.0'

target 'KWCacheKit_Example' do
  pod 'KWCacheKit', :path => '../'
  pod 'AFNetworking', '~> 2.3'

  target 'KWCacheKit_Tests' do
    inherit! :search_paths

    
  end
end
